import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )
}

// 7 diverse patient personas with complete intake answers
const PERSONAS = [
  {
    first_name: 'Rachel',
    last_name: 'Whitfield',
    email: 'dlolli@gmail.com',
    dob: '1975-06-22',
    phone: '(303) 555-0187',
    state: 'CO',
    answers: {
      full_name: 'Rachel Whitfield',
      dob: '1975-06-22',
      email: 'rachel.whitfield@gmail.com',
      phone: '(303) 555-0187',
      height: "5'7\"",
      weight: '162 lb',
      pcp: 'Dr. Amir Patel, Front Range Family Medicine',
      pharmacy: 'King Soopers Pharmacy, Lakewood CO',
      top_concern: 'I wake up drenched 3-4 times a night and I am exhausted all day. My brain feels like it is wrapped in cotton. I used to be so sharp at work and now I second-guess everything.',
      priorities: ['Hot flashes / night sweats', 'Sleep', 'Brain fog', 'Energy'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'Skipped periods',
      lmp: '2026-01-10',
      cycle_changes: ['Went 60+ days without a period', 'Periods came more than a week earlier or later'],
      abnormal_bleeding: ['None of these'],
      bp_known: 'Yes',
      bp_sys: 128,
      bp_dia: 82,
      current_meds: ['Thyroid medication', 'Antidepressant / anti-anxiety'],
      meds_detail: 'Levothyroxine 75mcg daily for hypothyroidism (stable 4 years). Lexapro 10mg daily started 8 months ago — takes the edge off anxiety but hasn\'t helped sleep or hot flashes. Vitamin D 2000IU, magnesium glycinate 400mg at night.',
      allergies: 'No',
      peanut: 'No',
      cardio: ['High blood pressure'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['None of these'],
      hf_freq: '6–10 per day',
      hf_sleep: 'Most nights',
      hf_severity: 'Severe',
      hf_duration: '3–5 minutes',
      hf_interference: 'Significantly',
      hf_assoc: ['Heart racing or palpitations', 'Chills after the hot flash'],
      palpitations: 'Moderate',
      joint_pain: 'Mild',
      sleep_falling: 'Moderate',
      sleep_waking: 'Severe',
      wired_tired: 'Severe',
      low_mood: 'Moderate',
      irritability: 'Severe',
      anxiety: 'Moderate',
      brain_fog: 'Severe',
      fatigue: 'Severe',
      sexual_change: 'Moderate',
      gsm: ['Vaginal dryness or burning'],
      bladder_sev: 'Mild',
      vaginal_sev: 'Moderate',
      midsection: 'Yes',
      strength: 'No',
      protein: 60,
      alcohol: 5,
      fracture: 'No',
      parent_hip: 'No',
      family_osteo: 'Yes',
      dexa: 'Never had one',
      bc_need: 'It probably matters',
      treatments_tried: 'Tried black cohosh for 3 months — no change. Evening primrose oil did nothing. Lexapro helped anxiety but not the flashes or sleep.',
      tx_openness: ['Hormone therapy', 'Non-hormonal prescription options'],
      dosing_pref: 'Weekly',
      open_notes: 'I\'m nervous about hormones because my mother had breast cancer at 72, but she also had a very different health profile than me. I\'m willing to discuss it openly. I just need to sleep again.',
    },
  },
  {
    first_name: 'Danielle',
    last_name: 'Okafor',
    email: 'dlolli@gmail.com',
    dob: '1970-11-03',
    phone: '(720) 555-0234',
    state: 'CO',
    answers: {
      full_name: 'Danielle Okafor',
      dob: '1970-11-03',
      email: 'danielle.okafor@gmail.com',
      phone: '(720) 555-0234',
      height: "5'4\"",
      weight: '178 lb',
      pcp: 'Dr. Lisa Chen, CU Medicine Primary Care',
      pharmacy: 'Walgreens, Aurora CO',
      top_concern: 'The rage is the worst part. I snap at my kids and my husband over nothing and then cry about it for an hour. I don\'t recognize myself anymore.',
      priorities: ['Mood', 'Sleep', 'Weight', 'Hot flashes / night sweats'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'No natural period for 12+ months',
      abnormal_bleeding: ['None of these'],
      bp_known: 'Yes',
      bp_sys: 134,
      bp_dia: 86,
      current_meds: ['Antidepressant / anti-anxiety'],
      meds_detail: 'Wellbutrin 150mg XL daily for 2 years — helped depression initially but wearing off. Ibuprofen 400mg as needed for joint pain (2-3x/week). Fish oil, B-complex, probiotics.',
      allergies: 'Yes',
      allergy_detail: 'Sulfa drugs — rash and swelling',
      peanut: 'No',
      cardio: ['High blood pressure', 'High cholesterol'],
      smoking: 'Past',
      cancer: 'No',
      other_conditions: ['None of these'],
      hf_freq: '3–5 per day',
      hf_sleep: '3–4 nights per week',
      hf_severity: 'Moderate',
      hf_duration: '1–3 minutes',
      hf_interference: 'Moderately',
      hf_assoc: ['Sudden anxiety or panic surge'],
      palpitations: 'Mild',
      joint_pain: 'Severe',
      sleep_falling: 'Moderate',
      sleep_waking: 'Severe',
      wired_tired: 'Severe',
      low_mood: 'Severe',
      irritability: 'Very severe / debilitating',
      anxiety: 'Severe',
      brain_fog: 'Moderate',
      fatigue: 'Severe',
      sexual_change: 'Severe',
      gsm: ['Vaginal dryness or burning', 'Pain with sex'],
      bladder_sev: 'Mild',
      vaginal_sev: 'Severe',
      midsection: 'Yes',
      strength: 'Yes',
      strength_days: 2,
      protein: 70,
      alcohol: 3,
      fracture: 'No',
      parent_hip: 'Unsure',
      family_osteo: 'Unsure',
      dexa: 'Never had one',
      bc_need: 'It does not matter',
      treatments_tried: 'My PCP increased the Wellbutrin to 300mg for a while but I got headaches. Tried melatonin and valerian for sleep — didn\'t help. Tried an OTC estrogen cream once but wasn\'t sure I was using it right.',
      tx_openness: ['Hormone therapy', 'Non-hormonal prescription options', 'Local vaginal treatment', 'Testosterone if appropriate'],
      dosing_pref: 'Longer-acting / low-maintenance',
      open_notes: 'I\'m a teacher and I cannot keep losing my temper with my students. This is affecting my career. I smoked socially in my 20s, quit completely at 30. I want to feel like myself again.',
    },
  },
  {
    first_name: 'Catherine',
    last_name: 'Brennan',
    email: 'dlolli@gmail.com',
    dob: '1968-02-14',
    phone: '(303) 555-0391',
    state: 'CO',
    answers: {
      full_name: 'Catherine Brennan',
      dob: '1968-02-14',
      email: 'catherine.brennan@gmail.com',
      phone: '(303) 555-0391',
      height: "5'9\"",
      weight: '145 lb',
      pcp: '',
      pharmacy: 'CVS Pharmacy, Cherry Creek Denver CO',
      top_concern: 'I had a hysterectomy 3 years ago and was put on estrogen but my doctor retired and nobody will refill my prescription. I feel like I\'m falling apart without it.',
      priorities: ['Hot flashes / night sweats', 'Energy', 'Mood', 'Brain fog', 'Sexual health'],
      uterus: 'No',
      ovaries: 'One ovary removed',
      menstrual: 'No periods — hysterectomy',
      abnormal_bleeding: ['None of these'],
      bp_known: 'Yes',
      bp_sys: 118,
      bp_dia: 74,
      current_meds: ['None of these'],
      meds_detail: 'WAS on estradiol patch 0.05mg twice weekly for 2 years — felt fantastic. Ran out 4 months ago when my prescribing doctor retired. Currently taking magnesium, vitamin D, calcium, and ashwagandha.',
      allergies: 'No',
      peanut: 'No',
      cardio: ['None of these'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['Endometriosis'],
      hf_freq: '6–10 per day',
      hf_sleep: 'Every night or multiple times',
      hf_severity: 'Very severe / debilitating',
      hf_duration: '3–5 minutes',
      hf_interference: 'Severely',
      hf_assoc: ['Heart racing or palpitations', 'Sudden anxiety or panic surge', 'Chills after the hot flash'],
      palpitations: 'Severe',
      joint_pain: 'Moderate',
      sleep_falling: 'Severe',
      sleep_waking: 'Very severe / debilitating',
      wired_tired: 'Very severe / debilitating',
      low_mood: 'Severe',
      irritability: 'Moderate',
      anxiety: 'Severe',
      brain_fog: 'Very severe / debilitating',
      fatigue: 'Very severe / debilitating',
      sexual_change: 'Very severe / debilitating',
      gsm: ['Vaginal dryness or burning', 'Pain with sex', 'Urinary urgency or frequency'],
      bladder_sev: 'Moderate',
      vaginal_sev: 'Very severe / debilitating',
      midsection: 'No',
      strength: 'Yes',
      strength_days: 4,
      protein: 100,
      alcohol: 2,
      fracture: 'No',
      parent_hip: 'Yes',
      family_osteo: 'Yes',
      dexa: 'Osteopenia',
      bc_need: 'It does not matter',
      treatments_tried: 'Estradiol patch 0.05mg for 2 years — worked perfectly. Since stopping: tried Remifemin (black cohosh), Relizen, and CBD oil for sleep. Nothing comes close to how I felt on the patch.',
      tx_openness: ['Hormone therapy', 'Local vaginal treatment', 'Testosterone if appropriate'],
      dosing_pref: 'Weekly',
      open_notes: 'I already know HRT works for me — I just need a provider who will prescribe it. I\'m also concerned about my bone density given the osteopenia result and family history. I\'m very active (Pilates 4x/week, hiking) and want to stay that way.',
    },
  },
  {
    first_name: 'Priya',
    last_name: 'Sharma',
    email: 'dlolli@gmail.com',
    dob: '1979-08-19',
    phone: '(720) 555-0456',
    state: 'CO',
    answers: {
      full_name: 'Priya Sharma',
      dob: '1979-08-19',
      email: 'priya.sharma@gmail.com',
      phone: '(720) 555-0456',
      height: "5'3\"",
      weight: '138 lb',
      pcp: 'Dr. John Williams, Highlands Ranch Medical Group',
      pharmacy: 'Costco Pharmacy, Lone Tree CO',
      top_concern: 'My periods have become completely unpredictable and I\'m getting terrible anxiety that comes out of nowhere. I\'ve never had anxiety before in my life and it\'s terrifying.',
      priorities: ['Mood', 'Sleep', 'Brain fog', 'Hot flashes / night sweats'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'Periods earlier or later than usual',
      lmp: '2026-03-01',
      cycle_changes: ['Periods came more than a week earlier or later'],
      abnormal_bleeding: ['Bleeding between periods'],
      bp_known: 'Yes',
      bp_sys: 112,
      bp_dia: 72,
      current_meds: ['None of these'],
      meds_detail: 'No prescription medications. Taking ashwagandha, magnesium glycinate 400mg, vitamin D 4000IU, omega-3s, and a women\'s multivitamin.',
      allergies: 'No',
      peanut: 'No',
      cardio: ['Migraine with aura'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['None of these'],
      hf_freq: '1–2 per day',
      hf_sleep: '1–2 nights per week',
      hf_severity: 'Mild',
      hf_duration: 'Less than 1 minute',
      hf_interference: 'Slightly',
      hf_assoc: ['Sudden anxiety or panic surge'],
      palpitations: 'Moderate',
      joint_pain: 'None',
      sleep_falling: 'Severe',
      sleep_waking: 'Moderate',
      wired_tired: 'Severe',
      low_mood: 'Mild',
      irritability: 'Moderate',
      anxiety: 'Very severe / debilitating',
      brain_fog: 'Moderate',
      fatigue: 'Moderate',
      sexual_change: 'Mild',
      gsm: ['None of these'],
      bladder_sev: 'None',
      vaginal_sev: 'None',
      midsection: 'Unsure',
      strength: 'Yes',
      strength_days: 3,
      protein: 80,
      alcohol: 1,
      fracture: 'No',
      parent_hip: 'No',
      family_osteo: 'No',
      dexa: 'Never had one',
      bc_need: 'Pregnancy prevention still matters',
      treatments_tried: 'Only supplements so far. My PCP suggested an SSRI but I\'d like to explore whether this is hormonal first before going on an antidepressant.',
      tx_openness: ['Hormone therapy', 'Non-hormonal prescription options', 'Lifestyle-only first', 'Not sure yet'],
      dosing_pref: 'Daily',
      open_notes: 'I have migraines with aura about 2x/month — I know this affects hormone options. I\'m a software engineer and the brain fog and anxiety are making it hard to concentrate on complex problems. I\'d love to understand what\'s happening hormonally before jumping to treatment.',
    },
  },
  {
    first_name: 'Lisa',
    last_name: 'Drummond',
    email: 'dlolli@gmail.com',
    dob: '1972-04-30',
    phone: '(303) 555-0528',
    state: 'CO',
    answers: {
      full_name: 'Lisa Drummond',
      dob: '1972-04-30',
      email: 'lisa.drummond@gmail.com',
      phone: '(303) 555-0528',
      height: "5'6\"",
      weight: '195 lb',
      pcp: 'Dr. Marta Reyes, Denver Health',
      pharmacy: 'Walmart Pharmacy, Thornton CO',
      top_concern: 'I\'ve gained 35 pounds in 18 months and nothing I do makes a difference. I eat well, I walk every day, and the scale just keeps going up. My joints hurt so much I had to stop jogging.',
      priorities: ['Weight', 'Energy', 'Sleep', 'Mood', 'Brain fog'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'No natural period for 12+ months',
      abnormal_bleeding: ['None of these'],
      bp_known: 'Yes',
      bp_sys: 142,
      bp_dia: 90,
      current_meds: ['Antidepressant / anti-anxiety', 'Sleep medication'],
      meds_detail: 'Zoloft 100mg daily (3 years). Trazodone 50mg at bedtime for sleep (1 year). Metformin 500mg twice daily for prediabetes (6 months). Ibuprofen 600mg daily for joint pain. Vitamin D, calcium, turmeric.',
      allergies: 'Yes',
      allergy_detail: 'Codeine — nausea and vomiting',
      peanut: 'No',
      cardio: ['High blood pressure', 'High cholesterol', 'Diabetes'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['Sleep apnea'],
      hf_freq: '3–5 per day',
      hf_sleep: '3–4 nights per week',
      hf_severity: 'Moderate',
      hf_duration: '1–3 minutes',
      hf_interference: 'Moderately',
      hf_assoc: ['Heart racing or palpitations', 'Nausea'],
      palpitations: 'Moderate',
      joint_pain: 'Very severe / debilitating',
      sleep_falling: 'Moderate',
      sleep_waking: 'Moderate',
      wired_tired: 'Moderate',
      low_mood: 'Severe',
      irritability: 'Moderate',
      anxiety: 'Moderate',
      brain_fog: 'Severe',
      fatigue: 'Very severe / debilitating',
      sexual_change: 'Severe',
      gsm: ['Vaginal dryness or burning', 'Bladder leakage'],
      bladder_sev: 'Moderate',
      vaginal_sev: 'Moderate',
      midsection: 'Yes',
      strength: 'No',
      protein: 50,
      alcohol: 0,
      fracture: 'No',
      parent_hip: 'No',
      family_osteo: 'No',
      dexa: 'Never had one',
      bc_need: 'It does not matter',
      treatments_tried: 'Zoloft helped depression somewhat. Trazodone helps me fall asleep but I still wake up. Tried Weight Watchers, keto, intermittent fasting — lost a few pounds each time then gained it all back plus more.',
      tx_openness: ['Hormone therapy', 'Non-hormonal prescription options', 'Lifestyle-only first'],
      dosing_pref: 'No preference',
      open_notes: 'I was diagnosed with sleep apnea last year and use a CPAP. My A1C was 6.2 at my last check. I know my weight is a factor in everything but I genuinely cannot lose it no matter what I try. I\'m hoping there\'s a hormonal component that we can address.',
    },
  },
  {
    first_name: 'Angela',
    last_name: 'Torres-Kim',
    email: 'dlolli@gmail.com',
    dob: '1974-12-08',
    phone: '(720) 555-0672',
    state: 'CO',
    answers: {
      full_name: 'Angela Torres-Kim',
      dob: '1974-12-08',
      email: 'angela.torreskim@gmail.com',
      phone: '(720) 555-0672',
      height: "5'5\"",
      weight: '155 lb',
      pcp: '',
      pharmacy: 'Safeway Pharmacy, Boulder CO',
      top_concern: 'Sex is painful now and it\'s destroying my marriage. I also have no desire whatsoever. My husband thinks I\'m not attracted to him anymore but it\'s entirely physical.',
      priorities: ['Sexual health', 'Vaginal symptoms', 'Mood', 'Energy'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'No natural period for 12+ months',
      abnormal_bleeding: ['None of these'],
      bp_known: 'No',
      current_meds: ['None of these'],
      meds_detail: 'No prescriptions. Using Replens vaginal moisturizer 3x/week. Coconut oil as lubricant. Vitamin D, evening primrose oil, maca root.',
      allergies: 'No',
      peanut: 'Unsure',
      cardio: ['None of these'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['None of these'],
      hf_freq: '1–2 per day',
      hf_sleep: '1–2 nights per week',
      hf_severity: 'Mild',
      hf_duration: 'Less than 1 minute',
      hf_interference: 'Slightly',
      hf_assoc: ['None of these'],
      palpitations: 'None',
      joint_pain: 'Mild',
      sleep_falling: 'Mild',
      sleep_waking: 'Moderate',
      wired_tired: 'Mild',
      low_mood: 'Moderate',
      irritability: 'Mild',
      anxiety: 'Mild',
      brain_fog: 'Mild',
      fatigue: 'Moderate',
      sexual_change: 'Very severe / debilitating',
      gsm: ['Vaginal dryness or burning', 'Pain with sex', 'Frequent UTIs', 'Urinary urgency or frequency'],
      bladder_sev: 'Moderate',
      vaginal_sev: 'Very severe / debilitating',
      midsection: 'Unsure',
      strength: 'Yes',
      strength_days: 2,
      protein: 65,
      alcohol: 4,
      fracture: 'No',
      parent_hip: 'No',
      family_osteo: 'No',
      dexa: 'Normal',
      bc_need: 'It does not matter',
      treatments_tried: 'Replens — helps a little with daily dryness but not with sex. Tried a bunch of OTC lubricants. Evening primrose oil and maca — no noticeable difference.',
      tx_openness: ['Local vaginal treatment', 'Testosterone if appropriate', 'Hormone therapy'],
      dosing_pref: 'Longer-acting / low-maintenance',
      open_notes: 'I\'ve had 4 UTIs in the past year which never happened before. My previous doctor said vaginal dryness was "just part of aging" and to use more lubricant. I want someone who takes this seriously. This is affecting my relationship and my self-esteem.',
    },
  },
  {
    first_name: 'Margaret',
    last_name: 'Novak',
    email: 'dlolli@gmail.com',
    dob: '1966-09-25',
    phone: '(303) 555-0819',
    state: 'CO',
    answers: {
      full_name: 'Margaret Novak',
      dob: '1966-09-25',
      email: 'margaret.novak@gmail.com',
      phone: '(303) 555-0819',
      height: "5'2\"",
      weight: '128 lb',
      pcp: 'Dr. Robert Klein, Boulder Medical Center',
      pharmacy: 'Lucky\'s Pharmacy, Boulder CO',
      top_concern: 'I\'m 59 and wondering if it\'s too late to start hormone therapy. My hot flashes never went away and my bones are thinning. I feel like I missed my window and I\'m angry about it.',
      priorities: ['Hot flashes / night sweats', 'Energy', 'Brain fog', 'Sleep'],
      uterus: 'Yes',
      ovaries: 'Both ovaries present',
      menstrual: 'No natural period for 12+ months',
      abnormal_bleeding: ['None of these'],
      bp_known: 'Yes',
      bp_sys: 124,
      bp_dia: 78,
      current_meds: ['Thyroid medication'],
      meds_detail: 'Synthroid 88mcg daily. Alendronate (Fosamax) 70mg weekly for osteopenia. Calcium 1200mg + Vitamin D 5000IU daily. CoQ10, turmeric.',
      allergies: 'No',
      peanut: 'No',
      cardio: ['None of these'],
      smoking: 'Never',
      cancer: 'No',
      other_conditions: ['None of these'],
      hf_freq: '3–5 per day',
      hf_sleep: '3–4 nights per week',
      hf_severity: 'Moderate',
      hf_duration: '1–3 minutes',
      hf_interference: 'Moderately',
      hf_assoc: ['Chills after the hot flash'],
      palpitations: 'Mild',
      joint_pain: 'Moderate',
      sleep_falling: 'Mild',
      sleep_waking: 'Moderate',
      wired_tired: 'Moderate',
      low_mood: 'Mild',
      irritability: 'Mild',
      anxiety: 'Mild',
      brain_fog: 'Moderate',
      fatigue: 'Moderate',
      sexual_change: 'Moderate',
      gsm: ['Vaginal dryness or burning', 'Urinary urgency or frequency'],
      bladder_sev: 'Moderate',
      vaginal_sev: 'Moderate',
      midsection: 'No',
      strength: 'Yes',
      strength_days: 3,
      protein: 75,
      alcohol: 3,
      fracture: 'No',
      parent_hip: 'Yes',
      family_osteo: 'Yes',
      dexa: 'Osteopenia',
      bc_need: 'It does not matter',
      treatments_tried: 'Fosamax for 2 years — tolerating it but concerned about long-term use. Tried gabapentin briefly for hot flashes — made me too drowsy. Never tried HRT because my previous doctor said I was "past the window."',
      tx_openness: ['Hormone therapy', 'Non-hormonal prescription options', 'Local vaginal treatment'],
      dosing_pref: 'Weekly',
      open_notes: 'I\'m a retired professor and I\'ve done a lot of reading on the timing hypothesis and the WHI study reanalysis. I believe my previous doctor was operating on outdated information. My mother broke her hip at 74. I want to be proactive about my bone health and I want honest information about whether HRT is still an option for me at 59.',
    },
  },
]

export async function POST(req: Request) {
  // Simple auth check — require a secret or just check for dev/preview
  const { secret } = await req.json().catch(() => ({ secret: '' }))
  if (secret !== 'womenkind-seed-2026') {
    return NextResponse.json({ error: 'Invalid secret' }, { status: 401 })
  }

  const supabase = getSupabase()
  const results: any[] = []

  for (const persona of PERSONAS) {
    try {
      // 1. Create profile
      const { data: profile, error: profileErr } = await supabase
        .from('profiles')
        .insert({
          id: crypto.randomUUID(),
          first_name: persona.first_name,
          last_name: persona.last_name,
          email: persona.email,
          role: 'patient',
        })
        .select('id')
        .single()

      if (profileErr) throw profileErr

      // 2. Create patient
      const { data: patient, error: patientErr } = await supabase
        .from('patients')
        .insert({
          profile_id: profile.id,
          date_of_birth: persona.dob,
          phone: persona.phone,
          state: persona.state,
        })
        .select('id')
        .single()

      if (patientErr) throw patientErr

      // 3. Create intake with full answers, mark as submitted
      const submittedAt = new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString()
      const { data: intake, error: intakeErr } = await supabase
        .from('intakes')
        .insert({
          patient_id: patient.id,
          status: 'submitted',
          answers: persona.answers,
          started_at: new Date(new Date(submittedAt).getTime() - 30 * 60 * 1000).toISOString(),
          submitted_at: submittedAt,
        })
        .select('id')
        .single()

      if (intakeErr) throw intakeErr

      // 4. Create a subscription marked as paid (skip Stripe)
      await supabase.from('subscriptions').insert({
        patient_id: patient.id,
        plan_type: 'intake',
        status: 'active',
        current_period_end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      })

      // 5. Generate AI brief via the same function used in submit
      let briefGenerated = false
      const anthropicKey = process.env.ANTHROPIC_API_KEY
      if (anthropicKey) {
        try {
          const briefResponse = await fetch(`${getAppUrl(req)}/api/intake/submit`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ intakeId: intake.id, answers: persona.answers }),
          })
          briefGenerated = briefResponse.ok
        } catch (e) {
          // If calling the submit endpoint fails, try generating directly
          console.error(`Brief generation failed for ${persona.first_name}:`, e)
        }
      }

      results.push({
        name: `${persona.first_name} ${persona.last_name}`,
        profileId: profile.id,
        patientId: patient.id,
        intakeId: intake.id,
        briefGenerated,
      })
    } catch (err: any) {
      results.push({
        name: `${persona.first_name} ${persona.last_name}`,
        error: err.message,
      })
    }
  }

  return NextResponse.json({ seeded: results })
}

function getAppUrl(req: Request): string {
  const host = req.headers.get('host') || 'localhost:3000'
  const proto = host.includes('localhost') ? 'http' : 'https'
  return `${proto}://${host}`
}
